"use client";

import Link from "next/link";
import { Bell, BookOpen, Clock, Loader2, LogOut, Moon, Palette, ShieldCheck, Sun, TriangleAlert, UserRound } from "lucide-react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import api from "@/lib/api";
import { useAuth } from "@/context/AuthContext";
import { useTheme } from "@/context/ThemeContext";
import toast from "react-hot-toast";

type Preferences = { due_reminders: boolean; overdue_alerts: boolean; hold_ready_alerts: boolean; };
const alerts: Array<{ key: keyof Preferences; title: string; description: string; icon: typeof Clock }> = [
  { key: "due_reminders", title: "Due date reminders", description: "Show a reminder before a borrowed book is due.", icon: Clock },
  { key: "overdue_alerts", title: "Overdue alerts", description: "Keep overdue loans visible until they are returned.", icon: TriangleAlert },
  { key: "hold_ready_alerts", title: "Hold ready alerts", description: "See when a reserved book is ready for collection.", icon: BookOpen },
];

export default function ProfilePage() {
  const { user, logout, isAdmin } = useAuth(); const { theme, toggleTheme } = useTheme(); const queryClient = useQueryClient();
  const { data: preferences, isLoading } = useQuery<Preferences>({ queryKey: ["notification-preferences"], queryFn: () => api.get("/users/me/notification-preferences").then(response => response.data) });
  const toggle = async (key: keyof Preferences) => { if (!preferences) return; try { const { data } = await api.patch<Preferences>("/users/me/notification-preferences", { [key]: !preferences[key] }); queryClient.setQueryData(["notification-preferences"], data); toast.success("Your settings were saved."); } catch { toast.error("Could not save that setting."); } };
  const shortcuts = isAdmin ? [{ href: "/dashboard", label: "Today’s work queue", detail: "Due loans, overdue items, and pickups" }, { href: "/dashboard/books", label: "Catalog & inventory", detail: "Books, copies, and shelf details" }, { href: "/dashboard/members", label: "Member directory", detail: "Accounts and access" }, { href: "/dashboard/analytics", label: "Analytics", detail: "Library activity and trends" }] : [{ href: "/dashboard/books", label: "Browse catalog", detail: "Find and reserve available books" }, { href: "/dashboard/transactions", label: "My loans", detail: "Dates, renewals, and return receipts" }, { href: "/dashboard", label: "My dashboard", detail: "Your reservations and recommendations" }];
  return <div className="max-w-6xl space-y-6 sm:space-y-8">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Account</p><h1 className="mt-3 text-3xl sm:text-4xl font-bold tracking-tight text-white">Settings that work around you.</h1><p className="text-sm sm:text-base text-slate-400 mt-2">Manage your profile, library updates, workspace preferences, and quick access.</p></div><button onClick={logout} className="inline-flex w-fit items-center gap-2 rounded-xl border border-red-400/20 bg-red-500/10 px-4 py-2.5 text-sm font-semibold text-red-200 transition-colors hover:bg-red-500/20"><LogOut size={16} /> Sign out</button></header>
    <div className="grid xl:grid-cols-[.9fr_1.1fr] gap-5">
      <section className="glass p-5 sm:p-6"><div className="flex items-start gap-4"><div className="w-14 h-14 shrink-0 rounded-2xl bg-indigo-500/15 flex items-center justify-center text-indigo-300 font-bold text-xl">{user?.name?.[0]?.toUpperCase()}</div><div className="min-w-0"><p className="font-semibold text-white text-lg truncate">{user?.name}</p><p className="text-sm text-slate-400 truncate">{user?.email}</p><span className="inline-flex mt-3 rounded-full bg-white/5 border border-white/10 px-2.5 py-1 text-xs capitalize text-slate-300">{isAdmin ? "Library administrator" : "Library member"}</span></div></div><dl className="mt-6 space-y-3 border-t border-white/5 pt-5 text-sm"><div className="flex justify-between gap-4"><dt className="text-slate-500">Username</dt><dd className="text-slate-200">@{user?.username}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Account access</dt><dd className="text-emerald-400">Active</dd></div></dl></section>
      <section className="glass p-5 sm:p-6"><div className="flex items-center gap-2"><Palette size={18} className="text-indigo-400" /><h2 className="font-semibold text-white">Workspace appearance</h2></div><p className="mt-1 text-sm text-slate-400">Choose the reading environment that feels right for you.</p><div className="mt-5 grid sm:grid-cols-2 gap-3"><button onClick={() => theme !== "light" && toggleTheme()} className={`appearance-option ${theme === "light" ? "appearance-option-active" : ""}`}><Sun size={19} /><span><b>Light mode</b><small>Bright and focused</small></span></button><button onClick={() => theme !== "dark" && toggleTheme()} className={`appearance-option ${theme === "dark" ? "appearance-option-active" : ""}`}><Moon size={19} /><span><b>Dark mode</b><small>Easy on the eyes</small></span></button></div><div className="mt-6 rounded-2xl bg-white/3 border border-white/5 p-4"><p className="text-sm font-medium text-white">{isAdmin ? "Admin workspace" : "Member workspace"}</p><p className="text-xs leading-5 text-slate-400 mt-1">{isAdmin ? "Your account can manage circulation, catalog inventory, members, and analytics." : "Your account can browse the catalog, manage holds, view loans, and renew eligible books."}</p></div></section>
    </div>
    <div className="grid lg:grid-cols-[1.1fr_.9fr] gap-5"><section className="glass p-5 sm:p-6"><div className="flex items-center gap-2"><Bell size={18} className="text-indigo-400" /><h2 className="font-semibold text-white">Library alerts</h2></div><p className="mt-1 text-sm text-slate-400">Choose the account updates that should stay visible.</p><div className="mt-5 divide-y divide-white/5">{isLoading ? <div className="py-10 flex justify-center"><Loader2 className="animate-spin text-indigo-400" /></div> : alerts.map(({ key, title, description, icon: Icon }) => <div key={key} className="flex items-center justify-between gap-4 py-4 first:pt-0 last:pb-0"><div className="flex min-w-0 items-start gap-3"><Icon size={18} className="mt-0.5 shrink-0 text-slate-400" /><div><p className="text-sm font-medium text-white">{title}</p><p className="text-xs leading-5 text-slate-400 mt-0.5">{description}</p></div></div><button type="button" role="switch" aria-checked={preferences?.[key] ?? false} aria-label={title} onClick={() => toggle(key)} className={`setting-switch ${preferences?.[key] ? "bg-indigo-600" : "bg-slate-700"}`}><span className={preferences?.[key] ? "translate-x-6" : "translate-x-1"} /></button></div>)}</div></section>
      <section className="glass p-5 sm:p-6"><div className="flex items-center gap-2"><ShieldCheck size={18} className="text-indigo-400" /><h2 className="font-semibold text-white">Quick access</h2></div><p className="mt-1 text-sm text-slate-400">Shortcuts for the parts of Library Desk you use most.</p><div className="mt-5 space-y-2">{shortcuts.map(item => <Link key={item.href + item.label} href={item.href} className="block rounded-xl border border-white/5 bg-white/3 p-3.5 transition-colors hover:bg-white/5 hover:border-indigo-500/30"><p className="text-sm font-medium text-white">{item.label}</p><p className="mt-1 text-xs text-slate-400">{item.detail}</p></Link>)}</div></section></div>
  </div>;
}
