"use client";

import { useState } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowLeft, BookOpen, Eye, EyeOff, Lock, Loader2, Mail, UserRound } from "lucide-react";
import toast from "react-hot-toast";
import { useRouter } from "next/navigation";
import api from "@/lib/api";

function Field({ label, icon: Icon, children }: { label: string; icon: typeof Lock; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-200">{label}</span><span className="relative block"><Icon className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-500" size={17} />{children}</span></label>; }

export default function SignupPage() {
  const router = useRouter(); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!name || !email || !username || !password) return toast.error("Complete all fields to create your account."); setLoading(true); try { await api.post("/auth/signup", { name, email, username, password }); toast.success("Your account is ready. Please sign in."); router.push("/login"); } catch (error: any) { toast.error(error?.response?.data?.detail || "We could not create that account."); } finally { setLoading(false); } };
  return <main className="auth-shell min-h-screen"><Link href="/" className="auth-back"><ArrowLeft size={16} /> Back to home</Link><div className="auth-grid"><section className="auth-intro"><Link href="/" className="flex items-center gap-2.5 text-white font-semibold"><span className="brand-mark"><BookOpen size={19} /></span> Library Desk</Link><div className="mt-auto mb-auto"><p className="eyebrow">Start your reading journey</p><h1 className="mt-5 text-4xl sm:text-5xl font-bold tracking-[-0.04em] leading-tight text-white">One account for every library visit.</h1><p className="mt-5 max-w-md text-slate-300 leading-7">Create your member account to browse the catalog, reserve available books, and see your loan history in one calm workspace.</p></div></section><motion.section initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="auth-card"><div><p className="text-sm font-medium text-teal-200">Create account</p><h2 className="mt-2 text-3xl font-bold tracking-tight text-white">Join the library.</h2><p className="mt-2 text-sm text-slate-400">It takes less than a minute to get started.</p></div><form onSubmit={submit} className="mt-7 grid gap-4"><Field label="Full name" icon={UserRound}><input value={name} onChange={e => setName(e.target.value)} autoComplete="name" placeholder="Aayush Angal" className="input-control" /></Field><Field label="Email address" icon={Mail}><input type="email" value={email} onChange={e => setEmail(e.target.value)} autoComplete="email" placeholder="you@example.com" className="input-control" /></Field><Field label="Username" icon={UserRound}><input value={username} onChange={e => setUsername(e.target.value)} autoComplete="username" placeholder="Choose a username" className="input-control" /></Field><Field label="Password" icon={Lock}><input type={showPassword ? "text" : "password"} value={password} onChange={e => setPassword(e.target.value)} autoComplete="new-password" placeholder="At least 6 characters" className="input-control pr-12" /><button type="button" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword(!showPassword)} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-500 hover:text-teal-200">{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></Field><button disabled={loading} className="brand-button mt-2 w-full justify-center py-3.5 disabled:opacity-60">{loading && <Loader2 size={17} className="animate-spin" />}{loading ? "Creating account…" : "Create account"}</button></form><p className="mt-6 text-sm text-slate-400">Already registered? <Link href="/login" className="font-medium text-teal-200 hover:text-teal-100">Sign in</Link></p></motion.section></div></main>;
}
